print "Hello Subham"
print "How are you?"
print "Assuming that you are good..you always are"
print "Don't loose faith in your self"
print "you have come a long way from you had started"
print "If you are thinking that you are loosing the game"
print "remember the days you changed the way of tragedies the last moment"
print "You will conqure"
print "Just don't loose faith"
print "Be Bold"
print "Never stop seeking knowledge"
print "You are here just to change the world"
print "If you are getting through a tough time remember this is just a side effect of being awesome"
print "And if you are getting good time and started to think that you will repeat this everyday like most of the people on the earth do "
print "remember that you are not made for this"
print "You go Boy Rock the World."
